server:
  port: 8087
dubbo:
  registry:
    address: zookeeper://192.168.119.129:2181
  application:
    name: health_mobile
  protocol:
    name: dubbo
spring:
  redis:
    host: 192.168.119.130
    port: 6379
    jedis:
      pool:
        max-idle: 6    #最大空闲数
        max-active: 10 #最大连接数
        min-idle: 2    #最小空闲数